### ISSUE TITLE
Page Response Error: Page Format

### ISSUE THREAD

**Issue by verkaro** [ObieSource/larigot#4]
Hey, glad to see a project like this getting started. I wrote two pages: rules.txt and welcome.gmi, txt is text and of course I adhere to gemini markup for the gmi file.

Attempting to fetch these pages from larigot gives me a client URL Fetch Error: Failed to get header: failed to read header: EOF.

I am an end user and no coder. This is simple feedback and the question: is there a special document format?
I am running larigot locally on ubuntu and using the amfora client.

**Comment by FiskFan1999** [comment]
Dear verkaro, I'm sorry to hear this. But thank you for the description of the error, "failed to read header", as it gives me an idea of what might be the problem, and it is something I neglected to write in the documentation, and will hopefully add to the README file of this project soon.

As for the file itself, what I didn't mention is that the file has to include the gemini header on the first line, so if you made a simple file `welcome.txt` that said "Welcome to my server!" it would have to read

```
20 text/plain
Welcome to my server!
```

However, there is one more annoying thing to remember here...that the header line **must** end with a carriage return and newline (`\r\n`), even though the rest of the lines do not need to. This is required in the specification, I think. On Ubuntu I think that if you write an ordinary text file, each line ends with only a newline character, so this would also lead to a problem to do with the header.

Thanks, let me know if this works for you.

**Comment by verkaro** [comment]
Thanks. I opened the files in vim and in command mode entered: :set ff=dos 
That did it.

**Comment by FiskFan1999** [comment]
Great, i'm glad that fixed the problem. Closing now, please do open another thread if anything else pops up.
